### ISSUE TITLE
How to make request?

### ISSUE THREAD

**Issue by returnMaxLimiter** [yarsky-tgz/scraper-http-client-request#3]
Big hello to you! I saw your library and was immediately interested. Can you tell me how to send a request to the site?

**Comment by yarsky-tgz** [comment]
It is just wrapper around [request-promise-native](https://npmjs.com/package/request-promise-native)

So you can work same way with it, as with usual [`request-promise`](https://npmjs.com/package/request-promise)

**Comment by returnMaxLimiter** [comment]
that is, if I use request-promise, then your library will work automatically? I do not understand

**Comment by yarsky-tgz** [comment]
I mean you can work with client as with request-promise, because under the hood that's it:

```javascript
const Bottleneck = require('bottleneck')
const client = require('scraper-http-client-request')(new Bottleneck({
  maxConcurrent: 10, //concurrent requests at the same time
  minTime: 333 //slow down, limit rate to keep pause between requests, reead the [docs](https://npmjs.com/package/bottleneck)
}))

client('https://jsonplaceholder.typicode.com/todos/1')
  .then((data) => {
    console.log(data)
  });
```

minimal example with default options

**Comment by returnMaxLimiter** [comment]
Oh, thank you very much. Another question, is it OK to bypass CLoudFlare?

**Comment by returnMaxLimiter** [comment]
do you speak russia?

**Comment by yarsky-tgz** [comment]
> is it OK to bypass CLoudFlare?

This package just uses ability, provided by another package - [cloudflare-bypasser](https://npmjs.com/package/cloudflare-bypasser), if you have any questions - ask author.
